In [12]:
from IPython.display import display
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_blobs
from sklearn.datasets import make_moons
from sklearn.datasets import make_circles
from sklearn.datasets import load_iris

In [4]:
from sklearn.ensemble import GradientBoostingClassifier
X,y = make_circles(noise=0.25, factor=0.5, random_state=1)

y_named = np.array(['blue','red'])[y]

X_train, X_test, y_train_named, y_test_named = train_test_split(X,y_named,random_state=0)

gbrt = GradientBoostingClassifier(random_state=0)
gbrt.fit(X_train, y_train_named)

GradientBoostingClassifier(random_state=0)

In [5]:
type(y)

numpy.ndarray

In [6]:
y_named

array(['red', 'red', 'blue', 'red', 'red', 'blue', 'blue', 'red', 'red',
       'red', 'red', 'blue', 'red', 'red', 'red', 'blue', 'blue', 'blue',
       'red', 'blue', 'blue', 'red', 'red', 'red', 'blue', 'blue', 'red',
       'blue', 'blue', 'blue', 'red', 'red', 'red', 'red', 'red', 'blue',
       'blue', 'red', 'blue', 'blue', 'red', 'red', 'red', 'blue', 'red',
       'blue', 'blue', 'red', 'blue', 'red', 'blue', 'red', 'blue',
       'blue', 'red', 'blue', 'blue', 'red', 'blue', 'red', 'blue', 'red',
       'red', 'blue', 'blue', 'red', 'blue', 'red', 'blue', 'red', 'red',
       'blue', 'red', 'red', 'blue', 'red', 'blue', 'red', 'red', 'blue',
       'blue', 'blue', 'blue', 'blue', 'blue', 'red', 'blue', 'blue',
       'red', 'red', 'blue', 'blue', 'red', 'red', 'blue', 'red', 'blue',
       'red', 'blue', 'blue'], dtype='<U4')

In [8]:
print(X_test.shape)
print('결정 함수 결과 형태 : ',gbrt.decision_function(X_test).shape)

(25, 2)
결정 함수 결과 형태 :  (25,)


In [9]:
gbrt.decision_function(X_test)[:6]

array([ 4.13592603, -1.70169917, -3.95106099, -3.62609552,  4.28986642,
        3.66166081])

In [10]:
print(gbrt.decision_function(X_test) > 0)
print(gbrt.predict(X_test))

[ True False False False  True  True False  True  True  True False  True
  True False  True False False False  True  True  True  True  True False
 False]
['red' 'blue' 'blue' 'blue' 'red' 'red' 'blue' 'red' 'red' 'red' 'blue'
 'red' 'red' 'blue' 'red' 'blue' 'blue' 'blue' 'red' 'red' 'red' 'red'
 'red' 'blue' 'blue']


In [11]:
gbrt.predict_proba(X_test)

array([[1.57362639e-02, 9.84263736e-01],
       [8.45756526e-01, 1.54243474e-01],
       [9.81128693e-01, 1.88713075e-02],
       [9.74070327e-01, 2.59296728e-02],
       [1.35214212e-02, 9.86478579e-01],
       [2.50463747e-02, 9.74953625e-01],
       [9.99543275e-01, 4.56725221e-04],
       [1.61426376e-02, 9.83857362e-01],
       [2.48329911e-01, 7.51670089e-01],
       [3.20518935e-02, 9.67948107e-01],
       [9.98441637e-01, 1.55836338e-03],
       [1.35214212e-02, 9.86478579e-01],
       [1.98099245e-02, 9.80190075e-01],
       [7.68580365e-01, 2.31419635e-01],
       [2.50463747e-02, 9.74953625e-01],
       [9.84817480e-01, 1.51825198e-02],
       [7.73836215e-01, 2.26163785e-01],
       [9.80463909e-01, 1.95360915e-02],
       [1.73607896e-02, 9.82639210e-01],
       [1.61426376e-02, 9.83857362e-01],
       [1.61426376e-02, 9.83857362e-01],
       [3.41393574e-01, 6.58606426e-01],
       [6.30759509e-02, 9.36924049e-01],
       [9.34424749e-01, 6.55752512e-02],
       [8.661995

## 다중 분류

In [14]:
iris = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,random_state=0)

gbrt = GradientBoostingClassifier(learning_rate=0.01, random_state=0)
gbrt.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.01, random_state=0)

In [15]:
print(gbrt.decision_function(X_test).shape)
print(gbrt.decision_function(X_test)[:6, :])

(38, 3)
[[-1.94508029 -2.01517311  0.12762926]
 [-1.94762009  0.04959233 -1.86975822]
 [ 0.08367469 -2.01610565 -1.86744871]
 [-1.94508859 -2.01517311  0.12762926]
 [ 0.08367469 -2.01610565 -1.86744871]
 [-1.94508029 -2.01517311  0.12762926]]


In [16]:
print(np.argmax(gbrt.decision_function(X_test),axis=1))
print(gbrt.predict(X_test))

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [19]:
print(gbrt.predict_proba(X_test)[:6, :])
print(gbrt.predict_proba(X_test)[:6].sum(axis=1))

[[0.10122859 0.09437615 0.80439526]
 [0.10582615 0.77977861 0.11439524]
 [0.79076534 0.09685557 0.11237909]
 [0.10122783 0.09437623 0.80439594]
 [0.79076534 0.09685557 0.11237909]
 [0.10122859 0.09437615 0.80439526]]
[1. 1. 1. 1. 1. 1.]


In [21]:
print(np.argmax(gbrt.predict_proba(X_test),axis=1))
print(gbrt.predict(X_test))

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
